const { DataTypes } = require("sequelize");
const { sequelize } = require("../config/database");
const master_chemist = sequelize.define(
  "master_chemist",
  {
    chemist_id: {
      type: DataTypes.INTEGER,
      autoIncrement: true,
      primaryKey: true,
    },
    auth_key: { type: DataTypes.STRING, defaultValue: "0", unique: true },
    store_name: { type: DataTypes.STRING, allowNull: false },
    manager_name: DataTypes.STRING,
    mobile: { type: DataTypes.STRING, allowNull: false, unique: true },
    alternate_mobile: DataTypes.STRING,
    email: DataTypes.STRING,
    password: { type: DataTypes.STRING, defaultValue: "123456" },
    address: { type: DataTypes.STRING, allowNull: false },
    city: { type: DataTypes.STRING, allowNull: false },
    taluka: DataTypes.STRING,
    district: DataTypes.STRING,
    state: DataTypes.STRING,
    pincode: DataTypes.STRING,
    district_id: DataTypes.INTEGER,
    state_id: DataTypes.INTEGER,
    area_type: DataTypes.STRING,
    chemist_type: DataTypes.STRING,
    doctor_speciality: DataTypes.STRING,
    open_time: DataTypes.STRING,
    close_time: DataTypes.STRING,
    holiday: DataTypes.STRING,
    is_fullday: { type: DataTypes.INTEGER, defaultValue: 0 },
    delivery_start: DataTypes.STRING,
    delivery_end: DataTypes.STRING,
    minimum_amount: DataTypes.STRING,
    delivery_charge: DataTypes.STRING,
    discount: DataTypes.STRING,
    lat: { type: DataTypes.STRING, allowNull: false },
    lng: { type: DataTypes.STRING, allowNull: false },
    store_photo: DataTypes.TEXT,
    profile_photo: DataTypes.TEXT,
    last_login: DataTypes.DATE,
    create_date: DataTypes.DATE,
    device_id: DataTypes.TEXT,
    phone_verified: { type: DataTypes.INTEGER, defaultValue: 1 },
    is_delete: { type: DataTypes.INTEGER, defaultValue: 0 },
    is_verified: { type: DataTypes.INTEGER, defaultValue: 0 },
    is_member: { type: DataTypes.INTEGER, defaultValue: 0 },
    status: DataTypes.STRING,
    referal_code: DataTypes.STRING,
    refered_by: DataTypes.STRING,
    pan_number: DataTypes.STRING,
    dl_number: DataTypes.STRING,
    gst: DataTypes.STRING,
    update_date: DataTypes.DATE,
  },
  {
    timestamps: false,
    tableName: "master_chemist",
  }
);

module.exports = master_chemist;
