const { DataTypes } = require("sequelize");
const { sequelize } = require("../config/database");

const master_doctor = sequelize.define(
  "master_doctor",
  {
    doctor_id: {
      type: DataTypes.INTEGER,
      autoIncrement: true,
      primaryKey: true,
    },
    auth_key: DataTypes.STRING,
    doctor_code: DataTypes.STRING,
    doctor_name: { type: DataTypes.STRING, allowNull: false },
    speciality: { type: DataTypes.STRING, allowNull: false },
    sub_speciality: DataTypes.STRING,
    qualification: DataTypes.STRING,
    email_id: DataTypes.STRING,
    mobile: { type: DataTypes.STRING, defaultValue: "0" },
    mobile_other: DataTypes.STRING,
    category: { type: DataTypes.STRING, defaultValue: "NA" },
    practice_type: DataTypes.STRING,
    doctor_dob: DataTypes.DATE,
    clinic_name: DataTypes.STRING,
    address: { type: DataTypes.STRING, defaultValue: "NA" },
    doctor_area: DataTypes.STRING,
    doctor_city: DataTypes.STRING,
    doctor_district: DataTypes.STRING,
    doctor_state: { type: DataTypes.STRING, allowNull: false },
    pincode: { type: DataTypes.STRING, defaultValue: "0" },
    is_delete: { type: DataTypes.INTEGER, defaultValue: 0 },
    is_active: { type: DataTypes.INTEGER, defaultValue: 1 },
    is_approved: { type: DataTypes.INTEGER, defaultValue: 0 },
    is_updated: { type: DataTypes.INTEGER, defaultValue: 1 },
    approved_by: DataTypes.STRING,
    create_datem: DataTypes.DATE,
    update_date: DataTypes.DATE,
    reg_no: DataTypes.STRING,
    reg_from: DataTypes.STRING,
    reg_year: DataTypes.STRING,
    doctor_picture: DataTypes.TEXT,
    doctor_picture_thumb: DataTypes.TEXT,
    picture_update_time: DataTypes.DATE,
    clinic_phone: DataTypes.STRING,
    is_whatsapp_active: { type: DataTypes.INTEGER, defaultValue: 0 },
    is_sms_active: { type: DataTypes.INTEGER, defaultValue: 0 },
    is_email_active: { type: DataTypes.INTEGER, defaultValue: 0 },
    userfield_1: DataTypes.TEXT,
    userfield_2: DataTypes.TEXT,
    userfield_3: DataTypes.TEXT,
    cipla_empid: DataTypes.STRING,
    pre_spe: DataTypes.TEXT,
    create_date: DataTypes.DATE,
    brand_focused: DataTypes.STRING,
    is_targeted: { type: DataTypes.INTEGER, defaultValue: 0 },
    doctor_qualification: DataTypes.STRING,
    experience_year: DataTypes.STRING,
    doctor_lat: DataTypes.STRING,
    doctor_lng: DataTypes.STRING,
  },
  {
    tableName: "master_doctor",
    timestamps: false,
  }
);

module.exports = master_doctor;
