const { DataTypes } = require("sequelize");
const {sequelize} = require("../config/database"); // Import database connection

const stockist_master = sequelize.define("stockist_master", {
  stockist_id: { 
    type: DataTypes.INTEGER, 
    primaryKey: true, 
    autoIncrement: true 
  },
  stockist_key: { type: DataTypes.STRING, unique: true },
  company_id: { type: DataTypes.INTEGER, allowNull: true },
  division_id: { type: DataTypes.INTEGER, allowNull: true },
  stockist_category: { type: DataTypes.STRING, allowNull: false },
  stockist_name: { type: DataTypes.STRING, allowNull: false },
  class: { type: DataTypes.STRING, allowNull: true },
  sub_area: { type: DataTypes.STRING, allowNull: true },
  short_name: { type: DataTypes.STRING, allowNull: true },
  stockist_manager: { type: DataTypes.STRING, allowNull: false },
  stockist_address: { type: DataTypes.STRING, allowNull: false },
  stockist_area: { type: DataTypes.STRING, allowNull: false },
  stockist_city: { type: DataTypes.STRING, allowNull: false },
  stockist_district: { type: DataTypes.STRING, allowNull: true },
  stockist_state: { type: DataTypes.STRING, allowNull: false },
  stockist_pincode: { type: DataTypes.STRING, allowNull: true },
  stockist_region: { type: DataTypes.STRING, allowNull: false },
  stockist_zone: { type: DataTypes.STRING, allowNull: true },
  stockist_contact: { type: DataTypes.STRING, allowNull: true },
  stockist_mobile: { type: DataTypes.STRING, allowNull: false },
  stockist_email: { type: DataTypes.STRING, allowNull: true },
  org_id: { type: DataTypes.STRING, allowNull: true },
  user_code: { type: DataTypes.STRING, allowNull: true },
  GSTIN: { type: DataTypes.STRING, unique: true, allowNull: true },
  lat: { type: DataTypes.STRING, allowNull: true },
  lng: { type: DataTypes.STRING, allowNull: true },
  status: { type: DataTypes.TINYINT, defaultValue: 0 },
  address2: { type: DataTypes.STRING, allowNull: true },
  address3: { type: DataTypes.STRING, allowNull: true },
  address4: { type: DataTypes.STRING, allowNull: true },
  fax: { type: DataTypes.STRING, allowNull: true },
  dob: { type: DataTypes.STRING, allowNull: true },
  dow: { type: DataTypes.STRING, allowNull: true },
  contact_person: { type: DataTypes.STRING, allowNull: true },
  contact_person_mobile: { type: DataTypes.STRING, allowNull: true },
  create_date: { type: DataTypes.DATE, allowNull: false, defaultValue: DataTypes.NOW },
  update_date: { type: DataTypes.DATE, allowNull: true },
  is_delete: { type: DataTypes.TINYINT, defaultValue: 0 },
  is_active: { type: DataTypes.TINYINT, defaultValue: 1 },
  tl_dl_no_1: { type: DataTypes.STRING, allowNull: true },
  tl_dl_no_2: { type: DataTypes.STRING, allowNull: true },
  food_dl_no: { type: DataTypes.STRING, allowNull: true },
  dl_valid_date: { type: DataTypes.STRING, allowNull: true },
  dl_valid_date_1: { type: DataTypes.STRING, allowNull: true },
  pan_no: { type: DataTypes.STRING, allowNull: true },
  gst_no: { type: DataTypes.STRING, allowNull: true },
  monthly_turnover: { type: DataTypes.STRING, allowNull: true },
  current_companies: { type: DataTypes.TEXT, allowNull: true },
  connected_hospital: { type: DataTypes.STRING, allowNull: true },
  speciality_covering: { type: DataTypes.STRING, allowNull: true },
  salesboys_count: { type: DataTypes.STRING, allowNull: true },
  hq_id: { type: DataTypes.INTEGER, defaultValue: 0 }
}, {
  tableName: "stockist_master",
  timestamps: false,
});

module.exports = stockist_master;
